
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1
    url: jdbc:mysql://127.0.0.1:3306/restaurant?useUnicode=true&characterEncoding=utf-8
    hikari:
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 60
      minimum-idle: 10
  #去掉theymeleaf的HTML5效验
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

#配置日志信息
logging:
  level:
    root: info
    com.lzy.liujing.restaurant: debug

#配置mybatis
mybatis:
#配置驼峰命名转换
  configuration:
     map-underscore-to-camel-case: true
  #配置mapping文件路径
  mapper-locations: classpath:/mappings/**/*.xml
  type-aliases-package: tk.mybatis.springboot.model

#mapper插件配置
mapper:
    mappers:
        - tk.mybatis.mapper.common.Mapper
    mapper.not-empty: false
    mapper.identity: MYSQL
#pageHelper配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#配置项目访问端口和地址
server:
  port: 8080
  servlet:
    context-path: /restaurant
