
spring:
  #数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1
    url: jdbc:mysql://127.0.0.1:3306/restaurant?useUnicode=true&characterEncoding=utf-8
    hikari:
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 60
      minimum-idle: 10
  transaction:
    rollback-on-commit-failure: true
  #去掉theymeleaf的HTML5效验
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  #配置时间(接口将字符串映射到实体的date类型时会用到，不配置时间会有偏差)
  jackson: time-zone=GMT+8
  #表示所有的访问都经过静态资源路径
  mvc:
    static-path-pattern: /**
    #在这里配置静态资源路径，前面说了这里的配置是覆盖默认配置，
    #所以需要将默认的也加上否则static、public等这些路径将不能被当作静态资源路径，
    #在这个最末尾的file:${web.upload-path}之所有要加file:是因为指定的是一个具体的硬盘路径，
    #其他的使用classpath指的是系统环境变量
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-image-path}
#配置日志信息
logging:
  level:
    root: info
    com.lzy.liujing.restaurant: debug

#配置mybatis
mybatis:
#配置驼峰命名转换
  configuration:
     map-underscore-to-camel-case: true
  #配置mapping文件路径
  mapper-locations: classpath:/mappings/**/*.xml
  type-aliases-package: tk.mybatis.springboot.model

#mapper插件配置
mapper:
    mappers:
        - tk.mybatis.mapper.common.Mapper
    mapper.not-empty: false
    mapper.identity: MYSQL
#pageHelper配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#配置项目访问端口和地址
server:
  port: 8181
  servlet:
    context-path: /restaurant

web:
  upload-image-path: D:/restaurant/upload
